-- AlterTable
ALTER TABLE `Cliente` ADD COLUMN `createdAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `deletedAt` DATETIME(0) NULL,
    ADD COLUMN `updatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Turno` ADD COLUMN `createdAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `deletedAt` DATETIME(0) NULL,
    ADD COLUMN `updatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Vehiculo` ADD COLUMN `createdAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `deletedAt` DATETIME(0) NULL,
    ADD COLUMN `updatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);
